project_name: Fungi
exp_name: Fungi
use_wandb: False
train_root: /home/data1/lkd/CVPR_FUNGI/Fungi_data/Fungidata/DF20
val_root: /home/data1/lkd/CVPR_FUNGI/Fungi_data/Fungidata/DF20
data_size: 384
num_workers: 4
batch_size: 16
model_name: swin-t
pretrained: /home/data4/czp/FGVC2022_Snake/FGVC-PIM/result/exp4/backup/best_f1.pt
optimizer: SGD
max_lr: 0.01
wdecay: 0.0005
max_epochs: 50
warmup_batchs: 800
use_amp: True
use_fpn: True
fpn_size: 1536
use_selection: True
num_classes: 1572
num_selects: 
  layer1: 2048
  layer2: 512
  layer3: 128
  layer4: 32
use_combiner: True
lambda_b: 0.5
lambda_s: 0.0
lambda_n: 5.0
lambda_c: 1.0
update_freq: 1
log_freq: 100
eval_freq: 1

sched: plateau
epochs: 100
patience_epochs: 1
decay_rate: 0.5
lr: 0.001
min_lr: 1e-6
warmup_lr: 0.0001
warmup_epochs: 3
save_dir: './result/exp5/'